config/routes.rb
MovieTrailer::Application.routes.draw do
  resources :comments
  resources :trailers
  root 'movies#index'
  resources :movies
  resources :characters

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @comment = Comment.new
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :poster_url)
    end
end

app/helpers/movies/characters_helper.rb
module Movies::CharactersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Title", required: true, autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :year %><br>
    <%= f.text_field :year, class: "form-control", placeholder: "Year", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :poster_url %><br>
    <%= f.url_field :poster_url, class: "form-control", placeholder: "Poster Url", required: true %>
  </div>
  <div class="actions">
    <%= f.submit :submit, class: "btn btn-primary" %>
    <%= link_to 'Back', movies_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="row">
	<div class="col-md-4">
		<iframe id="ytplayer" type="text/html" width="340" height="290" src="http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com" frameborder="0"/>
		<%#= iframe_tag :ytplayer, type: "text/html", width: 640, height: 390, src: 'http://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1&origin=http://example.com', frameborder: 0 %>
	</div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= link_to '<i class="fa fa-pencil"></i> New'.html_safe, new_movie_url, class: "btn btn-primary" %>
    <% @movies.each do |m| %>
      <div><%= link_to "<h1>#{m.title}</h1>".html_safe, movie_path(m) %>
        <span class="pull-left"><%= m.poster_url %></span> <span class="pull-right"><%= m.year %></span>
      </div>
    <% end %>
  </div>
</div>
<h2>Let us know about your movie!</h2>
<div class="row">
	<div class="col-xs-12">
	<%= form_for(@comment) do |f| %>
	  <% if @comment.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

	      <ul>
	      <% @comment.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="form-group">
	    <%= f.label :subject %><br>
	    <%= f.text_field :subject, class: "form-control", placeholder: "Subject", required: true %>
	  </div>
	  <div class="form-group">
	    <%= f.label :email %><br>
	    <%= f.text_field :email, class: "form-control", placeholder: "Email", required: true %>
	  </div>
	  <div class="form-group">
	    <%= f.label :message %><br>
	    <%= f.text_area :message, class: "form-control", placeholder: "Message", required: true %>
	  </div>
	  <div class="actions">
	    <%= f.submit :submit, class: "btn btn-default" %>
	  </div>
	<% end %>
	</div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_movie_path(@movie) %> | <%= link_to 'Back', movies_path %>

<p>
  <h1><%= @movie.title %></h1>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p> 
	<h2>Characters</h2>
	<div class="row">
	  <% @movie.characters.each do |character| %>
	    <div class="col-xs-4">
	      <div>
	      <span><%= character.name %></span>
	      <div><%= image_tag character.photo_url, size: "100x100" %></div>
	      <%= link_to 'Show', character %> | <%= link_to 'Edit', edit_character_path(character) %> | <%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %>
	      <br>
	      <%= character.movie.title rescue "" %>
	      </div>      
	    </div>
	  <% end %>
	</div>
	<br>
</p>

<p> 
	<h2>Trailers</h2>
	<div class="row">
	  <% @movie.trailers.each do |trailer| %>
	    <div class="col-xs-4">
	      <div>
	      <span><%= link_to trailer.title, "/trailers/#{trailer.id}" %></span>
	      <br><%= trailer.movie.title rescue "" %>
	      <%= link_to 'Show', trailer %> | <%= link_to 'Edit', edit_trailer_path(trailer) %> | <%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %>
	      <br>
	      </div>      
	    </div>
	  <% end %>
	</div>
	<br>
</p>

<p>
	<div class="col-sm-5 col-sm-offset-2 col-md-6 col-md-offset-0">
	  <iframe id="ytplayer" type="text/html" width="650" height="350" src="<%="#{@movie.poster_url}?autoplay=0"%>" frameborder="0"/>
	</div>
</p>