config/routes.rb
MovieTrailer::Application.routes.draw do
  resources :comments
  resources :trailers
  root 'movies#index'
  resources :movies
  resources :characters

end

app/models/trailer.rb
# == Schema Information
#
# Table name: trailers
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  embed_url  :string(255)
#  movie_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Trailer < ActiveRecord::Base
	belongs_to :movie
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: [:show, :edit, :update, :destroy]

  # GET /trailers
  # GET /trailers.json
  def index
    @trailers = Trailer.all
  end

  # GET /trailers/1
  # GET /trailers/1.json
  def show
  end

  # GET /trailers/new
  def new
    @trailer = Trailer.new
  end

  # GET /trailers/1/edit
  def edit
  end

  # POST /trailers
  # POST /trailers.json
  def create
    @trailer = Trailer.new(trailer_params)

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trailer }
      else
        format.html { render action: 'new' }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trailers/1
  # PATCH/PUT /trailers/1.json
  def update
    respond_to do |format|
      if @trailer.update(trailer_params)
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trailer_params
      params.require(:trailer).permit(:title, :embed_url, :movie_id)
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_for(@trailer) do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
      <% @trailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :movie_id %><br>
    <%= f.select :movie_id,  options_for_select( Movie.all.map {|movie| [movie.title, movie.id]}, selected: @trailer.movie_id ), {prompt: "Select Movie"}, {class: "form-control", autofocus: true, required: true } %>
  </div>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", required: true, placehoder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :embed_url %><br>
    <%= f.text_field :embed_url, class: "form-control", required: true, placehoder: "Embed Url" %>
  </div>
  <div class="actions">
    <%= f.submit :save, class: "btn btn-primary" %>
    <%= link_to 'Back', trailers_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing trailer</h1>

<%= render 'form' %>

app/views/trailers/index.html.erb
<h1>Listing trailers</h1>
<div class="row">
  <% @trailers.each do |trailer| %>
    <div class="col-xs-12">
      <span><h3><%= trailer.title %></h3></span>
      <br><%= trailer.movie.title rescue "" %>
      <%= link_to 'Show', trailer %> | <%= link_to 'Edit', edit_trailer_path(trailer) %> | <%= link_to 'Destroy', trailer, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'New Trailer', new_trailer_path %>

app/views/trailers/new.html.erb
<h1>New trailer</h1>

<%= render 'form' %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @trailer.title %>
</p>

<p>
  <strong>Embed url:</strong>
  <%= @trailer.embed_url %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @trailer.movie_id %>
</p>

<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>