config/routes.rb
MovieTrailer::Application.routes.draw do
  resources :comments
  resources :trailers
  root 'movies#index'
  resources :movies
  resources :characters

end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo_url  :string(255)
#  created_at :datetime
#  updated_at :datetime
#  movie_id   :integer
#

class Character < ActiveRecord::Base
	belongs_to :movie
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @characters = Character.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @character = Character.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @character }
      else
        format.html { render action: 'new' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :photo_url, :movie_id)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/movies/characters_helper.rb
module Movies::CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this movies_character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :movie_id %><br>
    <%= f.select :movie_id,  options_for_select( Movie.all.map {|movie| [movie.title, movie.id]}, selected: @character.movie_id ), {prompt: "Select Movie"}, {class: "form-control", autofocus: true, required: true } %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url, class: "form-control", required: true %>
  </div>
  <div class="actions">
    <%= f.submit :save, class: "btn btn-primary" %>
    <%= link_to 'Back', characters_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing movies_character</h1>

<%= render 'form' %>

app/views/characters/index.html.erb
<h1>Listing movies_characters</h1>
<div class="row">
  <% @characters.each do |character| %>
    <div class="col-xs-4">
      <div>
      <span><%= character.name %></span>
      <div><%= image_tag character.photo_url, size: "100x100" %></div>
      <%= link_to 'Show', character %> | <%= link_to 'Edit', edit_character_path(character) %> | <%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %>
      <br>
      <% if character.movie.present? %>
        <%= link_to character.movie.title, "/movies/#{character.movie.id}" %>
      <% end %>
      </div>      
    </div>
  <% end %>
</div>
<br>
<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @character.movie %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @character.photo_url %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>